name: Update repository
on:
  workflow_dispatch:
  schedule:
    - cron: 37 * * * *
jobs:
  update-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Install Node.js
        with:
          node-version: '16'

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Update apps.json
        run: |
          node update-apps.js https://apps.altstore.io ./news.json ./apps.json ./apps-safe.json https://nickchan.gq/altstore-beta/apps{,-safe}.json

      - name: Commit & push changes if there is changes
        run: |
          git config --global user.name "AltStore Beta"
          git config --global user.email actions@github.com
          git add .
          git diff-index --quiet HEAD || (git commit -am "apps.json, apps-safe.json: Update apps" && git push)
