name: Update repository
on:
  workflow_dispatch:
  schedule:
    - cron: 37 * * * *
jobs:
  update-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Install pnpm
        run: |
          curl -fsSL https://get.pnpm.io/install.sh | sh -
          echo "$HOME/.local/share/pnpm" >> $GITHUB_PATH

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install dependencies
        run: |
          pnpm i --frozen-lockfile

      - name: Update apps.json
        run: |
          node update-apps.js https://apps.altstore.io ./news.json ./apps.json ./apps-safe.json https://nickchan.gq/altstore-beta/apps{,-safe}.json
      - name: Commit & push changes if there is changes
        run: |
          git config --global user.name "AltStore Beta"
          git config --global user.email actions@github.com
          git add .
          git diff-index --quiet HEAD || (git commit -am "apps.json, apps-safe.json: Update apps" && git push)
