name: Update repository
on:
  workflow_dispatch:
  schedule:
    - cron: 37 * * * *
jobs:
  update-apps:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Update apps.json
        run: ./update-apps

      - name: Commit & push changes if there is changes
        run: |
          git config --global user.name "AltStore Beta"
          git config --global user.email actions@github.com
          git add .
          git diff-index --quiet HEAD || (git commit -am "apps.json, apps-safe.json: Update apps" && git push)
